[config]

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.wlogout]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.waybar]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.swaync]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.swayosd]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/swayosd/colors.css"
post_hook = "killall -9 swayosd-server && swayosd-server"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"
